# Generated by Django 5.0.6 on 2024-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('crt_part_number', models.CharField(max_length=200)),
            ],
        ),
    ]
