# Generated by Django 5.0.6 on 2024-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='lot_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
