# Generated by Django 5.0.6 on 2024-06-10 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_component_lot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
